kind: Secret
apiVersion: v1
metadata:
  name: acm-htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: '{{hub fromSecret "policies" "acm-htpass-secret" "htpasswd" hub}}'
--
kind: OAuth
apiVersion: config.openshift.io/v1
metadata:
  name: cluster
spec:
  identityProviders:
  - name: acm-htpasswd-provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: acm-htpass-secret
--
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-acm-tmm
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: acmuser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
